sonar.projectKey=L1nkiZ_dev-cloud
sonar.projectName=dev-cloud
sonar.sources=backend/src,client/src
sonar.tests=backend/spec,client/src
sonar.test.inclusions=backend/spec/**/*.js,client/src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,client/coverage/lcov.info
sonar.sourceEncoding=UTF-8
