apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-cloud-config
  namespace: dev-cloud
data:
  MYSQL_HOST: "mysql"
  MYSQL_USER: "root"
  MYSQL_DB: "todos"
  NODE_ENV: "production"
  PORT: "3000"
  AUTH_SERVICE_URL: "http://0.0.0.0:3001"
  AUTH_SERVICE_PORT: "3001"
  VITE_API_URL: "http://0.0.0.0/api"
  VITE_BACKEND_URL: "http://0.0.0.0"
  # VITE_AUTH_SERVICE_URL: "http://0.0.0.0:3001"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
  namespace: dev-cloud
data:
  default.conf: |
    server {
      listen 80;
      
      location / {
        proxy_pass http://frontend:5173/;
      }

      location /auth/ {
        proxy_pass http://auth-service:3001/;
      }

      location /api/ {
        proxy_pass http://backend:3000/;
      }
    }