apiVersion: v1
kind: Secret
metadata:
  name: dev-cloud-secret
  namespace: dev-cloud
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "secret"
  MYSQL_PASSWORD: "secret"
  JWT_SECRET: "PzsqTDaTiSx0LHbDbk842mKY1svpyDNFi2zHd1xo8It"
