###################################################
# Deployment — Frontend (React Frontend)
# The frontend connects to backend and auth-service.
###################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: client:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://0.0.0.0/api"
            - name: VITE_BACKEND_URL
              value: "http://0.0.0.0"
            # - name: VITE_AUTH_SERVICE_URL
            #   value: "http://0.0.0.0:3001"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: dev-cloud-config
                  key: NODE_ENV
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
---
###################################################
# Service — Frontend (LoadBalancer)
# Exposes the frontend on port 5173
###################################################
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev-cloud
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
  type: LoadBalancer
